### PR TITLE
Skip encrypted_data if not present

### PR DESCRIPTION
**Pull request by eltiare**
I had to add this in order to parse an encrypted response from a Shibboleth server.

### CODE REVIEW

**Comment by benoist** [comment]
Could you write a testcase for this?

**Comment by eltiare** [comment]
Alright. The response I'm testing against looks like it only has one encrypted key but for some reason the code is finding two.

**Comment by benoist** [comment]
When I parsed the message yesterday I saw two encrypted keys in there, but the cipher values are the same.

**Comment by eltiare** [comment]
When I manually decrypt the response using the methods described in the README, it works fine. When I use the wrapper methods in libsaml, it errors out. I'm guessing it's a bug with libsaml? I don't have the foggiest as to what it might be though.

**Pull request closed without merging**
